# Generated by Django 5.0 on 2024-12-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verify_wallet',
            field=models.BooleanField(default=False, verbose_name='是否驗證錢包'),
        ),
    ]
