# Generated by Django 5.0 on 2024-12-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AD_api', '0002_rename_uploaded_at_video_upload_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='name',
        ),
    ]
